NUMPY VS PYTHON LIST

...1..consume less memory.
...2..fast as compared to the python list.
...3..convenient to use.

# importance of numpy in python

# difference between numpy array and list in python

In [1]:
%timeit [j**4 for j in range(1,9)]

2.86 µs ± 76.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [2]:
import numpy as np

%timeit np.arange(1,9)**4

1.91 µs ± 262 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# NUMPY CREATE ARRAY

ARRAY

In [3]:
import numpy as np

x = [1,2,3,4]

y = np.array(x)

print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


INPUT FROM USER

In [4]:
l = []

for i in range(1,5):
    int_l = int(input("enter:"))
    l.append(int_l)
    
print(np.array(l))

enter:11
enter:12
enter:12
enter:13
[11 12 12 13]


# TYPES OF ARRAY

In [5]:
      

import numpy as np

x = [1,2,3,4]

y = np.array(x)

print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


 2-D ARRAY

In [6]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])   
print(ar2)                                 
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


3-D ARRAY

In [7]:
ar3 = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(ar3)
print(ar3.ndim)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
2


N-D ARRAY

In [8]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# SPECIAL TYPE OF ARRAYS(FILLED WITH SPECIFIC VALUE)

Array filled with 0's

In [9]:
ar_zero = np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [10]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Array filled with 1's (ONES)

In [11]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


Create an (EMPTY) array

In [12]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


An array with a (RANGE) of elements

In [13]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


 Array (DIAGONAL) elements filled with 1's

In [14]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


(LINSPACE)

In [16]:
ar_lin = np.linspace(0,10,num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


# CREATING RANDOM VALUED ARRAYS

# RANDOM

#########  Rand()  ##########

In [17]:
var = np.random.rand(4)
print(var)

[0.70955678 0.53044807 0.79382402 0.78032512]


In [18]:
var1 = np.random.rand(2,5)
print(var1)

[[0.06236469 0.27534063 0.42679667 0.33036369 0.83776424]
 [0.64957371 0.13715437 0.17134827 0.97377958 0.23370793]]


####### randn()  ##########

In [19]:
var2 = np.random.randn(5)
print(var2)

[-0.73982194 -1.37514268 -0.80935793 -0.04740614 -1.60401838]


########### ranf()  #########

In [20]:
var3 = np.random.ranf()
print(var3)

0.9406632269663638


########## randint() ########

In [21]:
var4 = np.random.randint(5,20,5)
print(var4)

[18 18 10  7 12]


# DATA TYPES IN NUMPY ARRAY

In [22]:
var = np.array([1,2,3,4,5,6,7])
print("data type :",var.dtype)

data type : int32


In [23]:
var = np.array([1,2.0,3.9,4.6,5.5,6,7])
print("data type :",var.dtype)

data type : float64


In [24]:
var = np.array(["g","h","y",1,7,5])
print("data type :",var.dtype)

data type : <U11


In [25]:
var = np.array(["g","h","y"])
print("data type :",var.dtype)

data type : <U1


# list of charater that are used to represent dtype in numpy.

convert dtype 

In [26]:
x = np.array([1,2,3,6,4],dtype = np.int8)
print("data type:",x.dtype)

data type: int8


In [27]:
x = np.array([1,2,3,6,4],dtype = "f")
print("data type:",x.dtype)
print(x)

data type: float32
[1. 2. 3. 6. 4.]


In [28]:
x = np.array([1,2,3,6,4])

new = np.float32(x)
print("data type:",x.dtype)
print("data type:",new.dtype)
print(x)
print(new)

data type: int32
data type: float32
[1 2 3 6 4]
[1. 2. 3. 6. 4.]


In [29]:
x = np.array([1,2,3,6,4])

new = np.float32(x)
new1 = np.int_(new)
print("data type:",x.dtype)
print("data type:",new.dtype)
print("data type:",new1.dtype)
print(x)
print(new)
print(new1)

data type: int32
data type: float32
data type: int32
[1 2 3 6 4]
[1. 2. 3. 6. 4.]
[1 2 3 6 4]


In [30]:
x = np.array([1,2,3,4])

new1 = x.astype(float)
print(x)
print(new1)

[1 2 3 4]
[1. 2. 3. 4.]


# Shape and Reshape in NumPy

In [31]:
import numpy as np
var = np.array([[1,3,7],[3,4,5]])
print(var)

print()
print(var.shape)

[[1 3 7]
 [3 4 5]]

(2, 3)


In [32]:
var1 = np.array([1,2,3,4],ndmin=4)

print(var1)
print(var1.ndim)
print()
print(var1.shape)


[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


# RESHAPE

In [33]:
var1 = np.array([1,2,3,4,5,6])
print(var1)
print(var1.ndim)
print()

x = var1.reshape(3,2)
print(x)
print(x.ndim)


[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


# (reshape in 3 d)

In [34]:
var1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var1)
print(var1.ndim)
print()

x = var1.reshape(2,3,2)
print(x)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


# (RESHAPE 1-D to 3-D to 1-D)

In [35]:
var1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var1)
print(var1.ndim)
print()

x = var1.reshape(2,3,2)
print(x)
print(x.ndim)

print()
one = x.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# Arithmetic Operations in numpy

In [36]:
import numpy as np

var = np.array([1,2,3,4])
varadd = var+3
print(varadd)

[4 5 6 7]


In [37]:
var = np.array([1,2,3,4])
varadd = var-3
print(varadd)

[-2 -1  0  1]


In [38]:
var = np.array([1,2,3,4])
varadd = var*3
print(varadd)

[ 3  6  9 12]


In [39]:
var = np.array([1,2,3,4])
varadd = var/3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [40]:
var = np.array([1,2,3,4])
varadd = var%3
print(varadd)

[1 2 0 1]


In [41]:
var = np.array([1,2,3,4])
varadd = var**3
print(varadd)

[ 1  8 27 64]


In [42]:
var = np.array([1,2,3,4])
var1 = np.array([3,4,5,6])
varadd = var+var1
print(varadd)

[ 4  6  8 10]


In [43]:
var = np.array([1,2,3,4])
var1 = np.array([3,4,5,6])
varadd = np.add(var,var1)
print(varadd)

[ 4  6  8 10]


FOR 2-D ARRAY

In [44]:
var = np.array([[1,2,3,4],[1,2,3,4]])
var1 = np.array([[2,3,4,5],[6,7,8,9]])
varadd = var + var1
print(varadd)

[[ 3  5  7  9]
 [ 7  9 11 13]]


In [45]:
var = np.array([[1,2,3,4],[1,2,3,4]])
var1 = np.array([[2,3,4,5],[6,7,8,9]])
print(var)
print()
print(var1)
print()

varadd = var + var1
print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[2 3 4 5]
 [6 7 8 9]]

[[ 3  5  7  9]
 [ 7  9 11 13]]


OTHER ARITHMATIC FUNCTIONS

In [46]:
var = np.array([1,2,3,4,11,12,13,14])
print("min : ",np.min(var),np.argmin(var))
print()
print("max : ",np.max(var),np.argmax(var))
print()
print("sqrt: ",np.sqrt(var))

min :  1 0

max :  14 7

sqrt:  [1.         1.41421356 1.73205081 2.         3.31662479 3.46410162
 3.60555128 3.74165739]


In [47]:
var = np.array([1,2,3,4])
print(np.sin(var))
print()
print(np.cos(var))
print()
print(np.cumsum(var))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]

[ 1  3  6 10]


In [48]:
var = np.array([[1,2,3],[11,12,13]])
print(np.min(var,axis=0))

[1 2 3]


# BROADCASTING WITH NUMPY ARRAY

In [49]:
var = np.array([1,2,3,4])
print(var.shape)
print()
print(var)
print()
var1 = np.array([[3],[4],[5],[6]])
print(var1.shape)
print()
print(var1)
print()
print(var+var1)


(4,)

[1 2 3 4]

(4, 1)

[[3]
 [4]
 [5]
 [6]]

[[ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]


# INDEXING & SLICING

In [50]:
var = np.array([[5,2,8,6],[8,5,4,2]])
print(var)
print(var.ndim)
print(var[0,2])

[[5 2 8 6]
 [8 5 4 2]]
2
8


In [51]:
var = np.array([[[5,2,8,6],[8,5,4,2],[4,2,9,3]]])
print(var)
print(var.ndim)
print(var[0,2,1])

[[[5 2 8 6]
  [8 5 4 2]
  [4 2 9 3]]]
3
2


# SLICING

In [52]:
import numpy as np
var = np.array([5,2,8,6,81,50,4,12])
print(var)
print(var.ndim)
print(var[1:5])
print(var[1:])
print(var[:-1])
print(var[-1:])
print("stop:",var[1:5:2])

[ 5  2  8  6 81 50  4 12]
1
[ 2  8  6 81]
[ 2  8  6 81 50  4 12]
[ 5  2  8  6 81 50  4]
[12]
stop: [2 6]


In [53]:
import numpy as np
var = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])

print(var)
print()
print("8 to 5 :",var[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5 : [12 13 14 15]


# ITERATION IN NUMPY

In [54]:
var = np.array([[[1,2,3,4],[4,5,6,7],[9,8,7,6]]])
print(var)
print(var.ndim)
print()
for i in var:
    print(i)
print()

for i in var:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [4 5 6 7]
  [9 8 7 6]]]
3

[[1 2 3 4]
 [4 5 6 7]
 [9 8 7 6]]

1
2
3
4
4
5
6
7
9
8
7
6


nditer function(use insted of for loop)

In [55]:
var = np.array([[[1,2,3,4],[4,5,6,7],[9,8,7,6]]])
print(var)
print(var.ndim)
print()
for i in np.nditer(var):
    print(i)

[[[1 2 3 4]
  [4 5 6 7]
  [9 8 7 6]]]
3

1
2
3
4
4
5
6
7
9
8
7
6


if we change datatype

In [56]:
var = np.array([[[1,2,3,4],[4,5,6,7],[9,8,7,6]]])
print(var)
print(var.ndim)
print()
for i in np.nditer(var,flags=['buffered'],op_dtypes=["S"]):
    print(i)

[[[1 2 3 4]
  [4 5 6 7]
  [9 8 7 6]]]
3

b'1'
b'2'
b'3'
b'4'
b'4'
b'5'
b'6'
b'7'
b'9'
b'8'
b'7'
b'6'


indexing in for loop (np.ndenumerate())

In [57]:
var = np.array([[[1,2,3,4],[4,5,6,7],[9,8,7,6]]])

for i,d in np.ndenumerate(var):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 1, 3) 7
(0, 2, 0) 9
(0, 2, 1) 8
(0, 2, 2) 7
(0, 2, 3) 6


# COPY AND VIEW IN NUMPY ARRAY

In [58]:
var = np.array([[[1,2,3,4],[4,5,6,7],[9,8,7,6]]])
co = var.copy()
var[0:3]=40
print("var: ",var)
print()
print("var: ",co)


var:  [[[40 40 40 40]
  [40 40 40 40]
  [40 40 40 40]]]

var:  [[[1 2 3 4]
  [4 5 6 7]
  [9 8 7 6]]]


COPY = IF WE CHANGE DATA, NO CHANGE IN COPY DATA

In [59]:
var = np.array([[[1,2,3,4],[4,5,6,7],[9,8,7,6]]])
vi = var.view()
var[0:3]=40
print("var: ",var)
print()
print("view: ",vi)

var:  [[[40 40 40 40]
  [40 40 40 40]
  [40 40 40 40]]]

view:  [[[40 40 40 40]
  [40 40 40 40]
  [40 40 40 40]]]


VIEW = IF WE CHANGE DATA, THEIR IS CHANGE IN VIEW DATA

# JOIN AND SPLIT METHOD

In [60]:
var = np.array([1,2,3,4])
var1 = np.array([2,3,4,5])
ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 2 3 4 5]


In [61]:
var = np.array([[1,2,3,4],[1,2,3,4]])
var1 = np.array([[2,3,4,5],[6,7,8,9]])
ar = np.concatenate((var,var1))
ar_new = np.concatenate((var,var1),axis=1)
print(ar)
print()
print(ar_new)

[[1 2 3 4]
 [1 2 3 4]
 [2 3 4 5]
 [6 7 8 9]]

[[1 2 3 4 2 3 4 5]
 [1 2 3 4 6 7 8 9]]


STACK FUNCTION 
1) VERTICAL
2)HORIJONTLY
3)DIMAENSION

In [62]:
var = np.array([1,2,3,4])
var1 = np.array([2,3,4,5])
ar = np.stack((var,var1),axis=0)
print(ar)

[[1 2 3 4]
 [2 3 4 5]]


In [63]:
var = np.array([1,2,3,4])
var1 = np.array([2,3,4,5])
ar = np.stack((var,var1),axis=1)
ar0 = np.vstack((var,var1)) # columns
ar1 = np.hstack((var,var1)) # rows
ar2= np.dstack((var,var1)) # height
print(ar)
print()
print(ar0)
print()
print(ar1)
print()
print(ar2)

[[1 2]
 [2 3]
 [3 4]
 [4 5]]

[[1 2 3 4]
 [2 3 4 5]]

[1 2 3 4 2 3 4 5]

[[[1 2]
  [2 3]
  [3 4]
  [4 5]]]


# SPLIT ARRAY

In [64]:
var = np.array([1,2,3,4])

ar = np.array_split(var,3)
print(ar)
print()
print(ar[1])

[array([1, 2]), array([3]), array([4])]

[3]


In [65]:
var = np.array([[1,2],[3,4],[1,2],[8,9]])

ar = np.array_split(var,2,axis=0)
print(ar)

[array([[1, 2],
       [3, 4]]), array([[1, 2],
       [8, 9]])]


# NUMPY ARRAY FUNCTION (SEARCH, SORT, SEARCH SORTED, FILTER)

In [66]:
var = np.array([1,2,3,4,6,7,8,9])

ar = np.where((var%2)==0)
print(ar)

(array([1, 3, 4, 6], dtype=int64),)


#search sorted array = which perform a binary search in the array, and return the index where the specified value would be inserted tomaintain the search order



In [67]:
var = np.array([1,2,3,4,6,7,8,9])

ar = np.searchsorted(var,5)
print(ar)

4


In [68]:
var = np.array([1,2,3,4,6,7,8,9])

ar = np.searchsorted(var,[5,6,7],side = "right")
print(ar)

[4 5 6]


sorted array : ordered sequence is any sequence that has an order corresponding to elemnts, like numeric or alphabetical, ascending or descending.

In [69]:
var = np.array([1,2,3,4,6,7,8,9])


print(np.sort(var))

[1 2 3 4 6 7 8 9]


In [70]:
var = np.array(["e","fg","cv","ty"])


print(np.sort(var))

['cv' 'e' 'fg' 'ty']


filter function : getting some elements out of an existing array and creating a new array out of them.

In [71]:
var = np.array(["e","fg","cv","ty"])
f = [True,False,False,True]
new = var[f]

print(new)
print(type(new))

['e' 'ty']
<class 'numpy.ndarray'>


# Shuffle, Unique, Resize, Flatten, Ravel Functions

shuffle

In [72]:
var = np.array(["e","fg","cv","ty"])

np.random.shuffle(var)
print(var)

['ty' 'fg' 'cv' 'e']


unique

In [73]:
var = np.array(["e","cv","ty","cv","fg","cv","ty"])
x = np.unique(var,return_index=True,return_counts=True)

print(x)

(array(['cv', 'e', 'fg', 'ty'], dtype='<U2'), array([1, 0, 4, 2], dtype=int64), array([3, 1, 1, 2], dtype=int64))


resize

In [74]:
var = np.array(["e","cv","ty","cv","fg","cv","ty"])
x = np.resize(var,(2,3))

print(x)

[['e' 'cv' 'ty']
 ['cv' 'fg' 'cv']]


flatten , RAVEL

it convert 2-d to 1-d array 

ORDER(C, F, K, A)

In [75]:
var = np.array(["e","cv","ty","cv","fg","cv","ty"])
x = np.resize(var,(2,3))
print(x)
print()
print("flatten: ",x.flatten(order = "F"))
print("ravel: ",np.ravel(x,order = "F"))
print("ravel: ",np.ravel(x,order = "K"))

[['e' 'cv' 'ty']
 ['cv' 'fg' 'cv']]

flatten:  ['e' 'cv' 'cv' 'fg' 'ty' 'cv']
ravel:  ['e' 'cv' 'cv' 'fg' 'ty' 'cv']
ravel:  ['e' 'cv' 'ty' 'cv' 'fg' 'cv']


# INSERT AND DELETE FUNCTION

In [76]:
var = np.array([1,2,3,4])
print(var)
print()
x = np.append(var,65)
print(x)

[1 2 3 4]

[ 1  2  3  4 65]


In [77]:
var = np.array([[1,2,3],[5,7,9]])

x = np.insert(var,1,[22,33,44],axis= 0)
print(x)
print()
x1 = np.append(var,[[22,33,44]],axis= 0)
print(x1)

[[ 1  2  3]
 [22 33 44]
 [ 5  7  9]]

[[ 1  2  3]
 [ 5  7  9]
 [22 33 44]]


In [78]:
var = np.array([[1,2,3],[5,7,9]])

x = np.delete(var,1)
print(x)
print()



[1 3 5 7 9]



# MATRIX IN NUMPY

In [79]:
var = np.matrix([[1,2],[2,3]])
var1 = np.matrix([[2,3],[4,5]])

print(var)

print(type(var))
print()
print(var*var1)
print()
print(var.dot(var1))

[[1 2]
 [2 3]]
<class 'numpy.matrix'>

[[10 13]
 [16 21]]

[[10 13]
 [16 21]]


In [80]:
var = np.array([[1,2,3],[4,5,6]])
print(var)
print(type(var))
print()
print(var*var)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>

[[ 1  4  9]
 [16 25 36]]


# MATRIX FUNCTION IN NUMPY ARRAY

>> TRANSPOSE  <<<<<<

In [81]:
var = np.matrix([[1,2,3],[4,2,8]])
print(var)
print()
print(np.transpose(var))

[[1 2 3]
 [4 2 8]]

[[1 4]
 [2 2]
 [3 8]]


In [82]:
var = np.matrix([[1,2,3],[4,2,8]])
print(var.T)

[[1 4]
 [2 2]
 [3 8]]


>> SWAPAXES   <<<<<<<<

In [83]:
var = np.matrix([[1,2,3],[4,2,8]])
print(var)
print()
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 2 8]]

[[1 4]
 [2 2]
 [3 8]]


>> INVERSE  <<<<<<<<<

In [84]:
var = np.matrix([[1,2],[4,2]])
print(var)
print()
print(np.linalg.inv(var))

[[1 2]
 [4 2]]

[[-0.33333333  0.33333333]
 [ 0.66666667 -0.16666667]]


>>  POWER   <<<<<<<

In [85]:
var = np.matrix([[1,2],[4,2]])
print(var)
print()
print(np.linalg.matrix_power(var,2))

[[1 2]
 [4 2]]

[[ 9  6]
 [12 12]]


>>   DETERMINATE  <<<<<<<

In [89]:
var = np.matrix([[1,2],[4,2]])
print(var)
print()
print(np.linalg.det(var))

[[1 2]
 [4 2]]

-6.0
